
@api =http://localhost:1234
@drinks = /drinks

### DRINKS
GET {{api}}{{drinks}}

###

GET {{api}}{{drinks}}/66fd76a57174c86a21945972

###

POST {{api}}{{drinks}}
Content-Type: application/json

{
  "name": "tercio",
  "price":4.50,
  "description": "Esto es una bebida",
  "section_id": "66fd8c594c289e29691af7ae"
}

###

DELETE {{api}}{{drinks}}/66fd734790c072076706bbea

###

PUT {{api}}{{drinks}}/66f3c7cc25c26bf9eca9b3c4
Content-Type: application/json

{
  "name":"Salamanca"
}

### SECTIONS

GET {{api}}/sections

###

PUT {{api}}/sections/66fd776deba6b2212e2c923a
Content-Type: application/json

{
  "title": "aaaaan"
}

###

POST {{api}}/sections
Content-Type: application/json

{
  "title": "Sección 3"
}

###
DELETE {{api}}/sections
Content-Type: application/json



### ADMIN

GET {{api}}/admin


### 

POST {{api}}/admin
Content-Type: application/json

{
  "name": "vinos",
  "password": "1234contraseñasupersegura",
  "mail": "holamundo@gmail.com",
}
