
@api =http://localhost:1234

GET {{api}}/drinks

###

GET {{api}}/drinks/1 HTTP/1.1

###

POST {{api}}/drinks
Content-Type: application/json

{
  "name": "tercio",
  "price":4.50,
  "description": "Esto es una bebida"
},


###

DELETE {{api}}/drinks/1

###

PUT {{api}}/drinks/1
