
@api =http://localhost:1234
@drinks = /sections/drinks

### DRINKS
GET {{api}}{{drinks}}

###

GET {{api}}{{drinks}}/66f3c7cc25c26bf9eca9b3c4

###

POST {{api}}{{drinks}}
Content-Type: application/json

{
  "name": "Tercio",
  "price":4.50,
  "description": "Esto es una bebida",
  "section_id": "66f3ee3ccad48f27b193124b"
}

###

DELETE {{api}}{{drinks}}/1

###

PUT {{api}}{{drinks}}/66f3c7cc25c26bf9eca9b3c4
Content-Type: application/json

{
  "name":"Salamanca"
}

### SECTIONS

GET {{api}}/sections

###
POST {{api}}/sections
Content-Type: application/json

{
  "title": "Vinos"
}
###
DELETE {{api}}/sections
Content-Type: application/json



### ADMIN

GET {{api}}/admin


### 

POST {{api}}/admin
Content-Type: application/json

{
  "name": "vinos",
  "password": "1234contraseñasupersegura",
  "mail": "holamundo@gmail.com",
}
